---
dist: trusty
language: go
script:
  - chmod u+rwx -R ./app
  - cd app/blog
  - ./scripts/hugo
deploy:
  provider: pages
  local-dir: app/blog/public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
