---
dist: trusty
language: go
script:
    - cd app/blog
    - chmod u+x ./scripts/hugo
    - ./scripts/hugo
deploy:
  provider: pages
  local-dir: app/blog/public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  on:
    branch: master
