dist: trusty
language: go
install: go get github.com/gohugoio/hugo
script:
    - cd app/blog
    - hugo
deploy:
  provider: pages
  local-dir: app/blog/public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
