################################# Default configuration ###################
# provide your domain here
baseURL = "https://sogloarcadius.github.io/blog"
# theme
theme = "dot"
# site title
title = "Blog"
# disable language
disableLanguages = []

publishdir = "public"

[markup.goldmark.renderer]
unsafe = true

################################# navigation ################################




############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#03A9F4"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# call to action is default enabled
enable = false

############################## social links ##############################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/sogloarcadius"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/sogloarcadius"
  
[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/arcadius-soglo-275bb180/"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 2
home = "Home"
copyright = " © sogloarcadius"

# banner
[Languages.en.params.banner]
title = "Blog"
subtitle = "Find all my content published using key words"
bg_image = "images/chart.png"
placeholder = "Search content"



################################### French Language ######################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
weight = 1
home = "Accueil"
copyright = " © sogloarcadius"

# banner
[Languages.fr.params.banner]
title = "Blog"
subtitle = "Rechercher mes contenus publiés par mots clés"
bg_image = "images/chart.png"
placeholder = "Chercher par mots clés"
